### ISSUE TITLE
Missing control over queues when submitting to LSF

### ISSUE THREAD

**Issue by berland** [equinor/everest#14]
**Issue**
`everserver` and the actual jobs submitted to an LSF cluster are distributed over different queues onprem, this does not seem right:

```
JOBID   USER    STAT  QUEUE	 FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME
831306  f_scout RUN   mr         st-vgrid02  st-rsv19-19 everserver May 28 09:59
831356  f_scout RUN   normal     st-rsv19-19 st-rsa00-00 EGG        May 28 09:59
```

**Definition of done**
everserver and EGG jobs end up in the same queue given that that is the intention.

**Comment by DanSava** [comment]
Reproduced the behaviour if without setting quename is not set in the simulator config setting 

```
simulator:
  queue_system: lsf
  cores: 100
  max_runtime: 10000
  resubmit_limit: 0
```

The user-recommended config is the following:

```
simulator:
  name: mr
  queue_system: lsf
....
```

When setting the queue name to:
```
simulator:
  name: mr
```
All jobs are distributed on the same queue onprem

```
JOBID   USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME
999729  dsav    RUN   mr         st-vgrid02  st-rsv18-18 everserver May 29 09:30
999789  dsav    RUN   mr         st-rsv18-18 st-rsa00-00 EGG        May 29 09:30

```
