### ISSUE TITLE
Naming of CSV-export file

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everest#74]
There was a user request to have `case_name` be the name of the exported CSV-file, however that is just a convention, and not an Everest keyword, however there is the option to configure the exported file name.

We should check that we can use the `case_name` definition in the name of the exported file.

**Comment by roliveira** [comment]
I'm using an available configuration file after including the following key/values:

```yaml
definitions: 
    case_name: TEST_EXPORT_CASE
export:
    csv_output_filepath: r{case_name}.csv
    keywords: ["FOPT", "FWPT"]
```

And I find the `TEST_EXPORT_CASE.csv` in the `output` directory after running `everest export`. If `csv_output_filepath` is not specified, the config file basename (_e.g._ `config` from `config.yml`) is used instead.

Additional comments:
- The `*.csv` extension needs to be specified in the `csv_output_filepath`.
- You're allowed to specify paths, so something like `csv_output_filepath: r{{configpath}}/../export/r{{case_name}}.csv` works just fine.
